//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Exceptional for ReSharper")]
[assembly: System.Reflection.AssemblyDescription("Analyzes thrown and documented C# exceptions and suggests improvements.")]
[assembly: System.Reflection.AssemblyProduct("Exceptional")]
[assembly: System.Reflection.AssemblyCompany("ExceptionalDevs")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2019 ExceptionalDevs")]
[assembly: System.Reflection.AssemblyVersion("0.23.2.0")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("3628d589-e118-4c2c-bd8e-fdef6b6ed07c")]


