//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGears.ReSharper.Exceptional {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeGears.ReSharper.Exceptional.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage of catch-all clauses is not recommended. [Exceptional].
        /// </summary>
        internal static string HighLightCatchAllClauses {
            get {
                return ResourceManager.GetString("HighLightCatchAllClauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; exception is not documented in xml documentation. [Exceptional].
        /// </summary>
        internal static string HighLightNotDocumentedExceptions {
            get {
                return ResourceManager.GetString("HighLightNotDocumentedExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; exception is not thrown from documented method. [Exceptional].
        /// </summary>
        internal static string HighLightNotThrownDocumentedExceptions {
            get {
                return ResourceManager.GetString("HighLightNotThrownDocumentedExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swallowing exceptions in catch-all clause is not recommended. [Exceptional].
        /// </summary>
        internal static string HighLightSwallowingExceptions {
            get {
                return ResourceManager.GetString("HighLightSwallowingExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While throwing from catch clause include substituted exception as inner exception. [Exceptional].
        /// </summary>
        internal static string HighLightThrowingFromCatchWithoutInnerException {
            get {
                return ResourceManager.GetString("HighLightThrowingFromCatchWithoutInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include catched exception as inner exception [Exceptional].
        /// </summary>
        internal static string QuickFixIncludeInnerException {
            get {
                return ResourceManager.GetString("QuickFixIncludeInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add documentation for {0} exception [Exceptional].
        /// </summary>
        internal static string QuickFixInsertExceptionDocumentation {
            get {
                return ResourceManager.GetString("QuickFixInsertExceptionDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove redundant exception documentation [Exceptional].
        /// </summary>
        internal static string QuickFixRemoveExceptionDocumentation {
            get {
                return ResourceManager.GetString("QuickFixRemoveExceptionDocumentation", resourceCulture);
            }
        }
    }
}
