name: Nightly Build

env:
  PACKAGE_ID: ExceptionalDevs.Exceptional.Nightly
  PACKAGE_TITLE: Exceptional for ReSharper (Nightly)

on:
  repository_dispatch:
  push:
    types: build-nightly
  schedule:
    - cron:  '30 1 * * *'

jobs:
  build:
    name: Nightly Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: 'master'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout master
        if: success()
        run: git checkout master

      - name: Precondition
        if: success()
        run: .\build\precondition.ps1
        
      - name: Setup Environment Variables
        run: |
          $CurrentVersion = .\build\get-version.ps1
          $NupkgFile = ".\build\packages\${env:PACKAGE_ID}\.${CurrentVersion}.nupkg"
          $TagName = "v${CurrentVersion}_nightly"
          echo "::set-env name=VERSION::$CurrentVersion"
          echo "::set-env name=NUPKG_FILE::$NupkgFile"
          echo "::set-env name=TAG_NAME::$TagName"
        
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
        
      - name: Setup Nuget
        uses: warrenbuckley/Setup-Nuget@v1
      
      - name: Build
        if: success()
        run: |
          nuget restore ./src/Exceptional.sln
          msbuild ./src/Exceptional.sln /p:Configuration=Release /t:rebuild

      - name: Pack
        if: success()
        run: nuget pack .\build\ExceptionalDevs.Exceptional.nuspec -OutputDirectory .\build\packages -properties "PackageId=${env:PACKAGE_ID};PackageTitle=${env:PACKAGE_TITLE}"

      - name: Release
        if: success()
        run: |
          $Uri = "https://api.github.com/repos/${env:GITHUB_REPOSITORY}/releases"
          $Body = @{
            "tag_name" = ${env:TAG_NAME}
            "name" = "Nightly Build (${env:VERSION})"
            "prerelease" = $true
          }
          $Headers = @{
            "Authorization" = "token ${env:token}"
          }
          $JsonBody = $Body | ConvertTo-Json -Depth 4
          Invoke-WebRequest -Method "Post" -Uri $Uri -Body $JsonBody -Headers $Headers
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Update nightly.rev
        if: success()
        run: .\build\update-nightly-rev.ps1
      
      - name: Increment Version
        if: success()
        run: .\build\increment-version.ps1 0.0.0.1

      - name: Add & Commit
        if: success()
        run: |
          git config user.email actions@github.com
          git config user.name "GitHub Actions"
          git commit -a -m "Nightly Commit" --author="GitHub Actions<actions@github.com>"
          git status

      - name: Git Push
        if: success()
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
      
